# Generated by Django 5.0.7 on 2026-04-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('address_text', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.district')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('slots_total', models.PositiveIntegerField(default=1)),
                ('requires_car', models.BooleanField(default=False)),
                ('requires_night_shift', models.BooleanField(default=False)),
                ('requires_physical_work', models.BooleanField(default=False)),
                ('requires_heavy_lifting', models.BooleanField(default=False)),
                ('avoid_large_crowds_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.volunteerdirection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.event')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasktype')),
            ],
        ),
        migrations.CreateModel(
            name='EventPositionAvailabilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('time_of_day', models.CharField(choices=[('MORNING', 'Утро'), ('DAY', 'День'), ('EVENING', 'Вечер')], max_length=16)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_requirements', to='events.eventposition')),
            ],
            options={'unique_together': {('position', 'weekday', 'time_of_day')}, 'ordering': ['weekday', 'time_of_day']},
        ),
        migrations.CreateModel(
            name='EventPositionLanguageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.CharField(choices=[('BASIC', 'Базовый'), ('CONVERSATIONAL', 'Разговорный'), ('FLUENT', 'Свободный')], default='CONVERSATIONAL', max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.language')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirements', to='events.eventposition')),
            ],
            options={'unique_together': {('position', 'language')}},
        ),
        migrations.CreateModel(
            name='EventPositionOptionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.CharField(choices=[('BEGINNER', 'Начальный'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый'), ('PROFESSIONAL', 'Профессиональный')], default='BEGINNER', max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optional_skill_items', to='events.eventposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={'unique_together': {('position', 'skill')}},
        ),
        migrations.CreateModel(
            name='EventPositionRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.CharField(choices=[('BEGINNER', 'Начальный'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый'), ('PROFESSIONAL', 'Профессиональный')], default='BEGINNER', max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skill_items', to='events.eventposition')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={'unique_together': {('position', 'skill')}},
        ),
    ]
