# Generated by Django 5.0.7 on 2026-03-12 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerHours',
        ),
    ]
