# Generated by Django 5.0.7 on 2026-03-16 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('events', '0002_delete_volunteerhours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AddField(
            model_name='event',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.district'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_experience_level', models.IntegerField(choices=[(0, 'Нет опыта'), (1, 'Базовый'), (2, 'Средний'), (3, 'Продвинутый')], default=0)),
                ('requires_car', models.BooleanField(default=False)),
                ('requires_night_shift', models.BooleanField(default=False)),
                ('allows_other_districts', models.BooleanField(default=True)),
                ('volunteers_needed', models.PositiveIntegerField(default=1)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requirements', to='core.volunteerdirection')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='events.event')),
                ('optional_skills', models.ManyToManyField(blank=True, related_name='optional_for_events', to='core.skill')),
                ('preferred_availability_slots', models.ManyToManyField(blank=True, related_name='preferred_for_events', to='core.availabilityslot')),
                ('required_languages', models.ManyToManyField(blank=True, related_name='required_for_events', to='core.language')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_events', to='core.skill')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_requirements', to='core.tasktype')),
            ],
            options={
                'verbose_name': 'Требования к мероприятию',
                'verbose_name_plural': 'Требования к мероприятиям',
            },
        ),
        migrations.CreateModel(
            name='VolunteerHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
