# Generated by Django 5.0.7 on 2026-03-17 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_volunteerprofile_cancelled_assignments_count_and_more'),
        ('core', '0001_initial'),
        ('events', '0003_alter_event_options_event_district_event_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Подана'), ('REVIEWING', 'На рассмотрении'), ('SHORTLISTED', 'В шорт-листе'), ('APPROVED', 'Одобрена'), ('REJECTED', 'Отклонена'), ('WITHDRAWN', 'Отозвана')], default='APPLIED', max_length=20)),
                ('source', models.CharField(choices=[('SELF', 'Самоотклик'), ('MANUAL', 'Добавлено вручную'), ('MATCHING', 'Подобрано системой')], default='SELF', max_length=20)),
                ('match_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('motivation_text', models.TextField(blank=True, default='')),
                ('review_comment', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Заявка на позицию',
                'verbose_name_plural': 'Заявки на позиции',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('min_experience_level', models.IntegerField(choices=[(0, 'Нет опыта'), (1, 'Базовый'), (2, 'Средний'), (3, 'Продвинутый')], default=0)),
                ('requires_car', models.BooleanField(default=False)),
                ('requires_night_shift', models.BooleanField(default=False)),
                ('allows_other_districts', models.BooleanField(default=True)),
                ('slots_total', models.PositiveIntegerField(default=1)),
                ('slots_filled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('OPEN', 'Открыта'), ('FILLED', 'Укомплектована'), ('CLOSED', 'Закрыта'), ('CANCELLED', 'Отменена')], default='OPEN', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_positions', to='core.volunteerdirection')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='events.event')),
                ('optional_skills', models.ManyToManyField(blank=True, related_name='optional_for_positions', to='core.skill')),
                ('preferred_availability_slots', models.ManyToManyField(blank=True, related_name='preferred_slots_for_positions', to='core.availabilityslot')),
                ('required_languages', models.ManyToManyField(blank=True, related_name='required_languages_for_positions', to='core.language')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_positions', to='core.skill')),
                ('task_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_positions', to='core.tasktype')),
            ],
            options={
                'verbose_name': 'Позиция мероприятия',
                'verbose_name_plural': 'Позиции мероприятий',
                'ordering': ['event_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает подтверждения'), ('CONFIRMED', 'Подтверждено'), ('DECLINED', 'Отклонено волонтёром'), ('CANCELLED', 'Отменено'), ('COMPLETED', 'Завершено'), ('NO_SHOW', 'Неявка')], default='PENDING', max_length=20)),
                ('reliability_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='events.application')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.volunteerprofile')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventposition')),
            ],
            options={
                'verbose_name': 'Назначение на позицию',
                'verbose_name_plural': 'Назначения на позиции',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.eventposition'),
        ),
        migrations.DeleteModel(
            name='VolunteerHours',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('position', 'volunteer_profile'), name='uniq_assignment_per_position_and_volunteer'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('position', 'volunteer_profile'), name='uniq_application_per_position_and_volunteer'),
        ),
    ]
