# Generated by Django 5.0.7 on 2026-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_address_text_event_venue_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('applied', 'Отклик отправлен'), ('reviewed', 'Рассмотрена'), ('assigned', 'Назначен'), ('confirmed', 'Подтверждено'), ('declined', 'Отклонено'), ('completed', 'Завершено'), ('failed', 'Не выполнено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('applied', 'Отклик отправлен'), ('reviewed', 'Рассмотрена'), ('assigned', 'Назначен'), ('confirmed', 'Подтверждено'), ('declined', 'Отклонено'), ('completed', 'Завершено'), ('failed', 'Не выполнено')], default='assigned', max_length=20),
        ),
    ]
