# Generated by Django 5.0.7 on 2026-04-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('ORG', 'Организация'), ('VOLUNTEER', 'Волонтёр'), ('MODERATOR', 'Модератор')], default='VOLUNTEER', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('organization_name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='', max_length=24)),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('availability_start_date', models.DateField(blank=True, null=True)),
                ('availability_end_date', models.DateField(blank=True, null=True)),
                ('ready_for_night_shifts', models.BooleanField(default=False)),
                ('can_travel', models.BooleanField(default=False)),
                ('has_car', models.BooleanField(default=False)),
                ('physical_work_ok', models.BooleanField(default=True)),
                ('carry_heavy_ok', models.BooleanField(default=True)),
                ('restrictions_note', models.TextField(blank=True, default='')),
                ('avoid_night_shifts', models.BooleanField(default=False)),
                ('avoid_outdoor_winter_work', models.BooleanField(default=False)),
                ('avoid_large_crowds', models.BooleanField(default=False)),
                ('participation_goal', models.CharField(blank=True, choices=[('RESUME', 'Опыт для резюме'), ('SOCIAL', 'Социальная миссия'), ('PRACTICE', 'Практика от вуза'), ('CERTIFICATE', 'За сертификат / благодарственное письмо')], default='', max_length=32)),
                ('motivation_text', models.TextField(blank=True, default='')),
                ('completed_events_count', models.PositiveIntegerField(default=0)),
                ('volunteer_hours', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('coordinator_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('response_speed_hours', models.PositiveIntegerField(default=0)),
                ('profile_completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.district')),
                ('preferred_directions', models.ManyToManyField(blank=True, related_name='preferred_by_volunteers', to='core.volunteerdirection')),
                ('preferred_task_types', models.ManyToManyField(blank=True, related_name='preferred_by_volunteers', to='core.tasktype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BASIC', 'Базовый'), ('CONVERSATIONAL', 'Разговорный'), ('FLUENT', 'Свободный')], default='CONVERSATIONAL', max_length=20)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to='core.language')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.volunteerprofile')),
            ],
            options={'unique_together': {('volunteer_profile', 'language')}},
        ),
        migrations.CreateModel(
            name='VolunteerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')])),
                ('time_of_day', models.CharField(choices=[('MORNING', 'Утро'), ('DAY', 'День'), ('EVENING', 'Вечер')], max_length=16)),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_items', to='accounts.volunteerprofile')),
            ],
            options={'unique_together': {('volunteer_profile', 'weekday', 'time_of_day')}, 'ordering': ['weekday', 'time_of_day']},
        ),
        migrations.CreateModel(
            name='VolunteerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BEGINNER', 'Начальный'), ('INTERMEDIATE', 'Средний'), ('ADVANCED', 'Продвинутый'), ('PROFESSIONAL', 'Профессиональный')], default='BEGINNER', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profiles', to='core.skill')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.volunteerprofile')),
            ],
            options={'unique_together': {('volunteer_profile', 'skill')}},
        ),
    ]
