# Generated by Django 5.0.7 on 2026-03-16 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_level', models.IntegerField(choices=[(0, 'Нет опыта'), (1, 'Базовый'), (2, 'Средний'), (3, 'Продвинутый')], default=0)),
                ('has_car', models.BooleanField(default=False)),
                ('ready_for_night_shifts', models.BooleanField(default=False)),
                ('can_travel_to_other_districts', models.BooleanField(default=False)),
                ('short_bio', models.CharField(blank=True, default='', help_text='Не используется в matching, только для интерфейса', max_length=255)),
                ('is_profile_completed', models.BooleanField(default=False)),
                ('profile_completion_percent', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_slots', models.ManyToManyField(blank=True, related_name='volunteers', to='core.availabilityslot')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.city')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='core.district')),
                ('languages', models.ManyToManyField(blank=True, related_name='volunteers', to='core.language')),
                ('preferred_directions', models.ManyToManyField(blank=True, related_name='volunteers', to='core.volunteerdirection')),
                ('preferred_task_types', models.ManyToManyField(blank=True, related_name='preferred_by_volunteers', to='core.tasktype')),
                ('skills', models.ManyToManyField(blank=True, related_name='volunteers', to='core.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета волонтёра',
                'verbose_name_plural': 'Анкеты волонтёров',
            },
        ),
    ]
