# Generated by Django 5.0.7 on 2026-03-17 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_options_volunteerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='cancelled_assignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='completed_assignments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Широта домашней/базовой точки волонтёра', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Долгота домашней/базовой точки волонтёра', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='is_available_for_matching',
            field=models.BooleanField(default=True, help_text='Временный флаг участия в подборе'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_assignment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='last_completed_assignment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Агрегированный показатель надёжности 0..100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
