# Generated by Django 5.0.7 on 2026-04-02 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена'), ('assigned', 'Назначен'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('failed', 'Не выполнено'), ('declined', 'Отклонено')], default='new', max_length=20)),
                ('motivation_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.eventposition')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.volunteerprofile')),
            ],
            options={
                'unique_together': {('position', 'volunteer_profile')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('reviewed', 'Рассмотрена'), ('assigned', 'Назначен'), ('confirmed', 'Подтверждено'), ('completed', 'Завершено'), ('failed', 'Не выполнено'), ('declined', 'Отклонено')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventposition')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.volunteerprofile')),
            ],
            options={
                'unique_together': {('position', 'volunteer_profile')},
            },
        ),
    ]
