from django.contrib import admin
from .models import Event, EventPosition, EventPositionRequiredSkill, EventPositionOptionalSkill, EventPositionLanguageRequirement, EventPositionAvailabilityRequirement
admin.site.register([Event, EventPosition, EventPositionRequiredSkill, EventPositionOptionalSkill, EventPositionLanguageRequirement, EventPositionAvailabilityRequirement])
